port: 7880
bind_addresses:
  - 0.0.0.0

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: true

redis:
  address: redis:6379

room:
  auto_create: true
  empty_timeout: 30
  departure_timeout: 20

logging:
  level: info

keys:
  APIkeyplaceholder: secretplaceholder
